version: "3.3"

services:
  mongo:
    image: mongo:7
    container_name: mongo_listing
    ports:
      - "27020:27017"
    volumes:
      - listing_mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - nginx-proxy-net
  app:
    container_name: listing_backend
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PORT=5050
    # expose:
    #   - "5050"
    volumes:
      - ./public:/usr/src/app/public
    # ports:
    #   - "5050:5050"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nginx-proxy-net
    depends_on:
      - mongo
  seed-admin:
    build:
      context: .
      dockerfile: Dockerfile.seed
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  listing_mongo_data:

networks:
  nginx-proxy-net:
    external: true
